// Login user
POST http://localhost:5000/login
Content-Type: application/json

{
      "email": "admin@gmail.com",
      "password": "123456"
}

###
// Get info user Login
GET http://localhost:5000/me

###
// Logout user
DELETE http://localhost:5000/logout


###
// Create a new user
POST http://localhost:5000/users
Content-Type: application/json

{
      "name": "Khoirul Husen",
      "email": "hoirul@gmail.com",
      "password": "123456",
      "confPassword": "123456",
      "role": "admin"
}

###
// Get all user
GET http://localhost:5000/users

###
// Get single user
GET http://localhost:5000/users/0387bae1-5134-4bdb-95eb-4c5dab64affe

###
// Updated user
PATCH http://localhost:5000/users/e95416b3-913b-4b9f-9b9d-71d186412d94
Content-Type: application/json

{
      "name": "Jhon Doe Updated",
      "email": "jhon@gmail.com",
      "password": "",
      "confPassword": "",
      "role": "user"
}

###
// Deleted user
DELETE http://localhost:5000/users/c3d6686a-ef76-471d-bda6-0b33b140efc1


###
// Created archive
POST http://localhost:5000/archives
Content-Type: application/json

{
      "name": "Data Kelurahan Admin",
      "link": "https://drive.google.com/data-kelurahan",
      "desc": "Ini adalah sebuah deskripsi dari tabel data arsip."
}

###
// Get all Archive
GET http://localhost:5000/archives

###
// Get single Archive
GET http://localhost:5000/archives/0fbffde2-6699-4247-bd58-44c4d18fab03

###
// Updated archive
PATCH http://localhost:5000/archives/7c1fb7a2-8eab-4c5d-b057-f807f8081cf2
Content-Type: application/json

{
      "name": "Data Kelurahan Admin Update 2",
      "link": "https://drive.google.com/data-kelurahan"
}

###
// Deleted archive
DELETE http://localhost:5000/archives/f87275a8-bd0a-4f03-99a5-9d4f5d472fd0

###
// Create Broadcast
POST http://localhost:5000/broadcast
Content-Type: application/json

{
      "title": "Kerja Bakti",
      "content": "Jangan Lupa untuk kegiatan kerja bakti esok hari"
}

###
// Get all Broadcast
GET http://localhost:5000/broadcast

###
// Delete Broadcast By Id
DELETE http://localhost:5000/broadcast/notif-Cc8HrZBNc

###
// Delete all Broadcast
DELETE http://localhost:5000/broadcast

###
// Create Event
POST http://localhost:5000/events
Content-Type: application/json

{
      "name": "Kerja Bakti",
      "desc": "Jangan Lupa untuk kegiatan kerja bakti esok hari",
      "date": "Jangan Lupa untuk kegiatan kerja bakti esok hari"
}

###
// Get all Events
GET http://localhost:5000/events

###
// Get single Event
GET http://localhost:5000/events/3a55440d-6e7e-4074-8eca-9f2ab01696aa

###
// Deleted Event
DELETE http://localhost:5000/events/3a55440d-6e7e-4074-8eca-9f2ab01696aa